name: course_module
description: Course module for DanXi app providing course management features
version: 1.0.0
publish_to: none # 将此模块标记为不可发布

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 1. 声明对原版库的依赖
  data_table_2: ^2.5.9
  flutter_typeahead: ^5.2.0
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.0.9
  sqflite: ^2.3.0 # 使用一个常规版本号
  
  # Local dependencies
  network:
    path: ../../common/network
  tools:
    path: ../../common/tools
  widgets:
    path: ../../common/widgets

# 2. 在这里强制覆盖为鸿蒙适配版
dependency_overrides:
  sqflite:
    git:
      # 注意：sqflite的仓库名是 flutter_sqflite
      url: https://gitee.com/openharmony-sig/flutter_sqflite.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
